export const sentenceTopics = ['PRESIDENTS', 'BASKETBALL', 'COSMOLOGY', 'SITCOMS', 'WAR', 'POLITICS',
    'COVID', 'FRUIT', 'YOUR FAVORITE SONG', 'MOVIES', 'CLIMATE CHANGE', 'YOUR FAVORITE BOOK',
    'JAZZ', 'CIVIL WAR', 'SUPREME COURT', 'SNOW STORMS', 'SPACE X', 'ON PROCRASTINATION']



